export declare const active: string;
export declare const btn: string;
export declare const dropdown: string;
export declare const item: string;
export declare const menu: string;
export declare const optionsBottomLeft: string;
export declare const optionsBottomRight: string;
export declare const optionsTopLeft: string;
export declare const optionsTopRight: string;
